### ISSUE TITLE
Troubles flashing with USB3 Ports

### ISSUE THREAD

**Issue by foosinn** [c0d3z3r0/aixun_t3x_updater#5]
Hey,

i almost though i had bricked my soldering station. 

When flashing from my Laptop i got this behavior:

```sh
$ sudo -g tty python t3xupdate.py ~/Downloads/JC_M_T320_1.12.bin
INFO: Update: T320 v1.12 (436480 bytes)
INFO: BL version: v0.02
Send update...0%...0%...0%...1%...1%...2%...2%...3%...3%...4%...4%...5%...5%...6%...6%...7%...7%...7%...8%...8%...9%...9%...10%...10%...11%...11%...12%...12%...13%...13%...14%...14%...15%...15%...ERROR: Update failed!
```

The error happening between 5 and 20%.

I was able to fix this simply by using a cheap USB 2.0 between my Laptop and the T320. Maybe this should be added to a troubleshooting section in the README?

Note: I've also experienced this with my st-link/v2 in the past.

**Comment by c0d3z3r0** [comment]
No worries, the stations have a bootloader that handles flashing. The bootloader is never getting overwritten, so if anything goes wrong, you can always reflash.

I never experienced such behaviour. Can you add a little more information, please? Laptop model, cable model, dock / no dock?

**Comment by foosinn** [comment]
Laptop model: Framework Intel 12th gen
Cable model: Unbranded A to C Cable
Docked: No


**Failes**: Framework -> Framework USB A Dongle -> USB A to USB C cable -> T320

**Works**: Framework -> Framework USB A Dongle -> Cheap USB 2.0 Hub -> USB A to USB C cable -> T320

Except for the hub everything else stayed the same.

**Comment by c0d3z3r0** [comment]
Hm, then it's not USB4 but USB3, right? (title says USB4)

Anyway, this *might* be a problem with that unbranded A-to-C cable. Some of them are a bit weird. Do you have a C-to-C cable you could test?

**Comment by foosinn** [comment]
Seems you are right, with the cable from pine64 flashing does not work, another one worked out. Still a bit strange that the Cable worked behind an USB 2.0 Hub.

Direct USB-C connection did not work at all, tried two cables that work with other devices.

I guess this can be closed, might also be a framework issue?

**Comment by c0d3z3r0** [comment]
I don't think it's a framework issue because you can't do USB3 wrong, well at least not *that* wrong like USB-C. But who knows ... :laughing:

**Comment by endeavour** [comment]
Uggh I had the same problem - wish I had seen this post earlier! It seems to be very sensitive to particular USB cables.
